# Generated by Django 3.2 on 2021-04-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt.sight')),
            ],
        ),
    ]
